name: Exploring variables and secrets

on: 
  push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: victorokoli
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Build
      run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker Login
      env:
        DOCKER_PASSWORD: ThaGreatest10
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

    - name: Docker Publish
      run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Container
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
