name: Generate ASCII network

on:
    workflow_dispatch:  
#    schedule:
#   - cron: "*/1 * * * *" 
 # push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 

      - name: List Repo files
        run: ls -ltra

      - name: Print working directory
        run: pwd

      - name: Check if ascii-script.sh exists
        run: |
          if [ -f ./ascii-script.sh ]; then
            echo "ascii-script.sh found"
          else
            echo "ascii-script.sh not found"
            exit 1
          fi
            
      - name: Executing shell script
        run: ./ascii-script.sh
