name: Matrix configuration

on:
    push

jobs:
   deploy:
      strategy:
          matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}   
           
      steps: 
       - name: echo Docker details
         run: docker info

       - name: Run images
         run: docker run ${{ matrix.images }} 

