name: workflow filters and activities.

on:
    # schedule:
    #   - cron: "*/30 * * * *"  
    push:
        branches: 
           - main
           - "!feature/*"

    pull_request:  
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main        

jobs:
    hello:
      runs-on: ubuntu-latest
      steps: 
       - run: echo this workflow/jobstep is executed for the event type - ${{ github.event }}
